hl.on("hyprland.start", function () 
  hl.exec_cmd("dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  --hl.exec_cmd("sleep 1 && hyprpm reload")
  hl.exec_cmd("yzshell &")
  hl.exec_cmd("nm-applet &")
  hl.exec_cmd("poweralertd &")
  hl.exec_cmd("udiskie &")
  hl.exec_cmd("wl-paste --watch cliphist store &")
  hl.exec_cmd("wayland-pipewire-idle-inhibit &")
  hl.exec_cmd("swayosd-server &")
  hl.exec_cmd("/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &")
  --hl.exec_cmd("~/.config/hypr/hyprland/scripts/portal.sh &")
  hl.exec_cmd("(hyprpm enable hyprbars; hyprpm reload) &")
  hl.exec_cmd("hypridle &")
  hl.exec_cmd("hyprctl setcursor " .. cursor_theme .. " 32")
end)