hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

hl.env("XCURSOR_SIZE", 32)
hl.env("GTK_THEME", "adw-gtk3")

hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", 1)
hl.env("QT_SCALE_FACTOR", 1)
hl.env("QT_ENABLE_HIGHDPI_SCALING", 0)
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)

hl.env("GDK_BACKEND", "wayland")
hl.env("CLUTTER_BACKEND", "wayland")
--hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("GDK_SCALE", 1)
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("_JAVA_AWT_WM_NONREPARENTING", 1)
hl.env("MOZ_ENABLE_WAYLAND", 1)
--hl.env("MOZ_USE_XINPUT2", 1)