hl.on("hyprland.start", function () 
  hl.exec_cmd("dbus-update-activation-environment")
  --hl.exec_cmd("sleep 1 && hyprpm reload")
  hl.exec_cmd("yzshell &")
  hl.exec_cmd("nm-applet &")
  hl.exec_cmd("poweralertd &")
  hl.exec_cmd("udiskie &")
  hl.exec_cmd("wl-paste --watch cliphist store &")
  hl.exec_cmd("wayland-pipewire-idle-inhibit &")
  hl.exec_cmd("swayosd-server &")
  hl.exec_cmd("/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &")
  --hl.exec_cmd("~/.config/hypr/hyprland/scripts/portal.sh &")
  hl.exec_cmd("~/.config/hypr/hyprland/scripts/plugins.sh &")
  hl.exec_cmd("~/.config/hypr/hyprland/scripts/idle.sh &")
end)