hl.bind("SUPER + Return", hl.dsp.exec_cmd(terminal))
hl.bind("SUPER + W", hl.dsp.exec_cmd(web_browser))
hl.bind("SUPER + E", hl.dsp.exec_cmd(file_manager))
hl.bind("SUPER + R", hl.dsp.exec_cmd(run_launcher))
hl.bind("SUPER + SHIFT + L", hl.dsp.exec_cmd("hyprlock"))

-- yzshell
hl.bind("SUPER + SHIFT + R", hl.dsp.exec_cmd("yzshell reload"), { submap_universal = true })
hl.bind("SUPER + P", hl.dsp.exec_cmd("yzwidgets toggle control_center"))
hl.bind("SUPER + SHIFT + C", hl.dsp.exec_cmd("yzwidgets toggle calendar"))
hl.bind("SUPER + SHIFT + Q", hl.dsp.exec_cmd("yzwidgets toggle power"))
hl.bind("SUPER + SHIFT + A", hl.dsp.exec_cmd("yzwidgets toggle settings"))
hl.bind("SUPER + Tab", hl.dsp.exec_cmd("yzwidgets toggle workspaces"))
hl.bind("SUPER + C", hl.dsp.exec_cmd("yzpicker"), { submap_universal = true })
hl.bind("SUPER + S", hl.dsp.exec_cmd("yzshot -m select"), { submap_universal = true })
hl.bind("SUPER + CTRL + S", hl.dsp.exec_cmd("yzshot -m full"), { submap_universal = true })
hl.bind("SUPER + ALT + S", hl.dsp.exec_cmd("yzwidgets toggle screenshot"))
hl.bind("SUPER + SHIFT + B", hl.dsp.exec_cmd("killall waybar; waybar &"), { submap_universal = true })
hl.bind("SUPER + SHIFT + D", hl.dsp.exec_cmd("yzshell cmd toggle_dnd"), { submap_universal = true })

hl.define_submap("control_center", function()
	hl.bind("escape", hl.dsp.exec_cmd("yzwidgets close all"))
	hl.bind("up", hl.dsp.exec_cmd("yzwidgets ctl control_center_search_selected prev"))
	hl.bind("down", hl.dsp.exec_cmd("yzwidgets ctl control_center_search_selected next"))
	hl.bind("SUPER + P", hl.dsp.exec_cmd("yzwidgets close all"))
end)

hl.define_submap("calendar", function()
	hl.bind("escape", hl.dsp.exec_cmd("yzwidgets close all"))
	hl.bind("SUPER + SHIFT + C", hl.dsp.exec_cmd("yzwidgets close all"))
end)

hl.define_submap("power", function()
	hl.bind("escape", hl.dsp.exec_cmd("yzwidgets close all"))
	hl.bind("l", hl.dsp.exec_cmd("yzwidgets close all; yzlock -g 0"))
	hl.bind("s", hl.dsp.exec_cmd("systemctl shutdown"))
	hl.bind("r", hl.dsp.exec_cmd("systemctl reboot"))
	hl.bind("e", hl.dsp.exec_cmd("hyprctl dispatch 'hl.dsp.exit()'"))
	hl.bind("SUPER + SHIFT + Q", hl.dsp.exec_cmd("yzwidgets close all"))
end)

hl.define_submap("screenshot", function()
	hl.bind("escape", hl.dsp.exec_cmd("yzwidgets close all"))
	hl.bind("SUPER + ALT + S", hl.dsp.exec_cmd("yzwidgets close all"))
end)

hl.define_submap("settings", function()
	hl.bind("escape", hl.dsp.exec_cmd("yzwidgets close all"))
	hl.bind("SUPER + SHIFT + A", hl.dsp.exec_cmd("yzwidgets close all"))
end)

hl.define_submap("workspaces", function()
	hl.bind("escape", hl.dsp.exec_cmd("yzwidgets close all"))
	hl.bind("Tab", hl.dsp.exec_cmd("yzwidgets close all"))
	hl.bind("SUPER + Tab", hl.dsp.exec_cmd("yzwidgets close all"))
	hl.bind("Return", hl.dsp.exec_cmd("yzwidgets close all"))
	hl.bind("left", function()
		hl.dispatch(hl.dsp.focus({ workspace = "e-1" }))
		hl.dispatch(hl.dsp.exec_cmd("eww poll workspaces"))
		hl.dispatch(hl.dsp.exec_cmd("eww poll active_workspace"))
	end)
	hl.bind("right", function()
		hl.dispatch(hl.dsp.focus({ workspace = "e+1" }))
		hl.dispatch(hl.dsp.exec_cmd("eww poll workspaces"))
		hl.dispatch(hl.dsp.exec_cmd("eww poll active_workspace"))
	end)
	hl.bind("up", function()
		hl.dispatch(hl.dsp.focus({ workspace = "e-1" }))
		hl.dispatch(hl.dsp.exec_cmd("eww poll workspaces"))
		hl.dispatch(hl.dsp.exec_cmd("eww poll active_workspace"))
	end)
	hl.bind("down", function()
		hl.dispatch(hl.dsp.focus({ workspace = "e+1" }))
		hl.dispatch(hl.dsp.exec_cmd("eww poll workspaces"))
		hl.dispatch(hl.dsp.exec_cmd("eww poll active_workspace"))
	end)
	for i = 1, 9 do
		hl.bind("SUPER + " .. i, function()
			hl.dispatch(hl.dsp.exec_cmd("eww poll workspaces"))
			hl.dispatch(hl.dsp.exec_cmd("eww poll active_workspace"))
			hl.dispatch(hl.dsp.focus({ workspace = i }))
		end)
		hl.bind(i, function()
			hl.dispatch(hl.dsp.exec_cmd("eww poll workspaces"))
			hl.dispatch(hl.dsp.exec_cmd("eww poll active_workspace"))
			hl.dispatch(hl.dsp.focus({ workspace = i }))
			hl.dispatch(hl.dsp.exec_cmd("yzwidgets close all"))
		end)
	end
end)
