hl.bind("SUPER + Return", hl.dsp.exec_cmd(terminal))
hl.bind("SUPER + W", hl.dsp.exec_cmd(web_browser))
hl.bind("SUPER + E", hl.dsp.exec_cmd(file_manager))
hl.bind("SUPER + R", hl.dsp.exec_cmd(run_launcher))

-- yzshell
hl.bind("SUPER + SHIFT + R", hl.dsp.exec_cmd("yzshell"))
hl.bind("SUPER + SHIFT + L", hl.dsp.exec_cmd("yzshell lock -g 0"))
hl.bind("SUPER + P", hl.dsp.exec_cmd("yzshell toggle control_center"))
hl.bind("SUPER + C", hl.dsp.exec_cmd("yzshell toggle calendar"))
hl.bind("SUPER + SHIFT + Q", hl.dsp.exec_cmd("yzshell toggle power"))
hl.bind("SUPER + SHIFT + A", hl.dsp.exec_cmd("yzshell toggle settings"))
hl.bind("SUPER + C", hl.dsp.exec_cmd("yzshell pick_colour"))
hl.bind("SUPER + S", hl.dsp.exec_cmd("yzshell screenshot -m select"))
hl.bind("SUPER + CTRL + S", hl.dsp.exec_cmd("yzshell screenshot -m full"))
hl.bind("SUPER + ALT + S", hl.dsp.exec_cmd("yzshell toggle screenshot"))
hl.bind("SUPER + SHIFT + B", hl.dsp.exec_cmd("killall waybar; waybar &"))

hl.define_submap("control_center", function()
    hl.bind("escape", hl.dsp.exec_cmd("yzshell close_all_widgets"))
    hl.bind("up", hl.dsp.exec_cmd("yzshell search_selected prev"))
    hl.bind("down", hl.dsp.exec_cmd("yzshell search_selected next"))
end)

hl.define_submap("calendar", function()
    hl.bind("escape", hl.dsp.exec_cmd("yzshell close_all_widgets"))
end)

hl.define_submap("power", function()
    hl.bind("escape", hl.dsp.exec_cmd("yzshell close_all_widgets"))
    hl.bind("l", hl.dsp.exec_cmd("yzshell close_all_widgets; yzshell lock -g 0"))
    hl.bind("s", hl.dsp.exec_cmd("systemctl shutdown"))
    hl.bind("r", hl.dsp.exec_cmd("systemctl reboot"))
    hl.bind("e", hl.dsp.exec_cmd("yzshell window_manager exit"))
end)

hl.define_submap("screenshot", function()
    hl.bind("escape", hl.dsp.exec_cmd("yzshell close_all_widgets"))
end)

hl.define_submap("settings", function()
    hl.bind("escape", hl.dsp.exec_cmd("yzshell close_all_widgets"))
end)